const LAST_UPDATED = '20 July 2026';
const CONTACT_EMAIL = 'dimisiet@gmail.com';
const DEVELOPER = 'NZEULIE SIETCHIPING DIMITRI';
const APP_NAME = 'Dano – Meal Planner';

function page(title: string, bodyHtml: string): string {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${title} — ${APP_NAME}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif; max-width: 720px; margin: 0 auto; padding: 32px 20px 80px; line-height: 1.6; color: #1a1a1a; }
  h1 { font-size: 26px; margin-bottom: 4px; }
  h2 { font-size: 18px; margin-top: 32px; }
  .updated { color: #666; font-size: 13px; margin-bottom: 32px; }
  ul { padding-left: 20px; }
  a { color: #2a6f2f; }
</style>
</head>
<body>
<h1>${title}</h1>
<p class="updated">Last updated: ${LAST_UPDATED}</p>
${bodyHtml}
</body>
</html>`;
}

export function termsHandler(_req: any, res: any) {
  res.status(200).type('html').send(page('Terms of Use', `
<p>These Terms of Use ("Terms") govern your use of ${APP_NAME} (the "App"), provided by ${DEVELOPER} ("we", "us"). By creating an account or using the App, you agree to these Terms.</p>

<h2>The Service</h2>
<p>${APP_NAME} generates personalized weekly meal plans using an AI model, based on information you provide (goals, dietary preferences, budget), and helps you shop for ingredients by matching them to promotional pricing at supermarkets such as Lidl. The App also lets you log meals, track nutrition, import recipes shared from third-party platforms (e.g. TikTok), and scan food or receipts using your device's camera.</p>

<h2>Accounts</h2>
<p>You sign in using Sign in with Apple. You are responsible for any activity under your account. You may delete your account at any time from Profile → Delete Account, which permanently removes your data — see our <a href="/legal/privacy">Privacy Policy</a>.</p>

<h2>Subscriptions</h2>
<p>${APP_NAME} offers an optional auto-renewing subscription ("dano Pro") unlocking the full weekly plan and additional features. Subscription length (monthly or annual) and price are shown before purchase. Payment is charged to your Apple ID account at confirmation of purchase. Subscriptions automatically renew unless auto-renew is turned off at least 24 hours before the end of the current period. You can manage or cancel your subscription in your Apple ID account settings at any time. No refund will be provided for the unused portion of a subscription period, except as required by applicable law.</p>

<h2>Nutrition disclaimer</h2>
<p>${APP_NAME} provides general nutrition and meal-planning information generated by an AI model. It is not medical advice and is not a substitute for guidance from a qualified physician, dietitian, or nutritionist — particularly if you have a medical condition, allergy, or are pregnant. Calorie and macro estimates are approximations. Always check ingredient labels for allergens before consuming any suggested meal.</p>

<h2>User content</h2>
<p>When you import a recipe (for example, from a TikTok link) or save a photo for food scanning, you confirm you have the right to share that content with us for the purpose of using the App's features. We do not claim ownership of content you submit.</p>

<h2>Acceptable use</h2>
<p>You agree not to misuse the App, attempt to disrupt its operation, or use it to violate any applicable law.</p>

<h2>Disclaimer &amp; liability</h2>
<p>The App is provided "as is" without warranties of any kind. To the maximum extent permitted by law, ${DEVELOPER} is not liable for any indirect or consequential damages arising from your use of the App.</p>

<h2>Changes</h2>
<p>We may update these Terms from time to time. Continued use of the App after changes take effect constitutes acceptance of the revised Terms.</p>

<h2>Contact</h2>
<p>Questions about these Terms can be sent to <a href="mailto:${CONTACT_EMAIL}">${CONTACT_EMAIL}</a>.</p>
`));
}

export function privacyHandler(_req: any, res: any) {
  res.status(200).type('html').send(page('Privacy Policy', `
<p>This Privacy Policy explains what data ${APP_NAME} (the "App") collects, why, and how it's handled. The App is provided by ${DEVELOPER} ("we", "us").</p>

<h2>Information we collect</h2>
<ul>
  <li><strong>Account information</strong>: your name and email, provided via Sign in with Apple (which may be a private relay address if you choose to hide your email).</li>
  <li><strong>Profile &amp; nutrition data</strong>: age, height, weight, fitness goal, activity level, dietary restrictions/preferences, weekly grocery budget, household size, and kitchen equipment — all entered by you to personalize meal plans.</li>
  <li><strong>App content</strong>: generated meal plans, saved recipes, meal ratings and notes, grocery/pantry list state, and recipes you import from third-party links.</li>
  <li><strong>Photos</strong>: if you use the food/receipt-scanning feature, the photo you capture or select is sent for analysis as described below. We do not retain a copy of these photos on our servers beyond what's needed to return a result.</li>
  <li><strong>Purchase information</strong>: subscription status and purchase history, handled by Apple and RevenueCat (see below) — we do not receive or store your payment card details.</li>
  <li><strong>Health data (optional)</strong>: if you grant permission, the App may read step-count data from Apple Health to refine your activity-level estimate, and write meals you log as consumed calories back to Apple Health. This only happens if you explicitly grant HealthKit permission, and this data is not sent to our servers — it stays between your device and Apple Health.</li>
</ul>

<h2>How we use your information</h2>
<p>We use your profile and preference data to generate personalized meal plans and recommendations (via Anthropic's Claude AI models), match ingredients to supermarket promotions, and operate core app features such as meal logging, ratings-based plan improvement, and grocery lists.</p>

<h2>Third parties we share data with</h2>
<ul>
  <li><strong>Anthropic (Claude API)</strong> — receives your stated preferences, dietary restrictions, and (if you use food-scanning) photos, in order to generate meal plans and analyze food/receipt images.</li>
  <li><strong>Supabase</strong> — hosts our database and authentication; stores your account and app data securely.</li>
  <li><strong>RevenueCat</strong> — manages subscription status and receipt validation on our behalf.</li>
  <li><strong>Apple</strong> — provides Sign in with Apple, processes App Store payments, and (if enabled) Apple Health integration.</li>
  <li><strong>Railway</strong> — hosts our backend server infrastructure.</li>
</ul>
<p>We do not sell your personal data.</p>

<h2>Data retention &amp; deletion</h2>
<p>We retain your data for as long as your account is active. You can permanently delete your account and all associated data (profile, meal plans, recipes, ratings, grocery state) at any time from Profile → Delete Account within the App. This action is immediate and irreversible.</p>

<h2>Children's privacy</h2>
<p>${APP_NAME} is not directed at children under 16, and we do not knowingly collect personal information from them.</p>

<h2>Your rights</h2>
<p>Depending on where you live (including under the EU/UK GDPR), you may have rights to access, correct, or delete your personal data, or to object to certain processing. You can exercise deletion directly in the App, or contact us for other requests.</p>

<h2>Changes to this policy</h2>
<p>We may update this Privacy Policy from time to time. Material changes will be reflected by updating the "Last updated" date above.</p>

<h2>Contact</h2>
<p>Questions about this Privacy Policy or your data can be sent to <a href="mailto:${CONTACT_EMAIL}">${CONTACT_EMAIL}</a>.</p>
`));
}
